[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npx prisma migrate deploy && npm run build && npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

